[package]
name = "lokimcp-server"
version.workspace = true
edition.workspace = true
publish.workspace = true
description = "Loki MCP — server binary"

[[bin]]
name = "lokimcp-server"
path = "src/main.rs"

[dependencies]
# keep-sorted start
color-eyre.workspace = true
dotenvy.workspace = true
lokimcp = { path = "../lokimcp" }
mcp-common = { path = "../../common/mcp-common" }
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
# keep-sorted end
