name: Security Audit

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  cargo-deny-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: cargo-deny advisories
        run: nix develop --command cargo deny check advisories
      - name: cargo-deny bans
        run: nix develop --command cargo deny check bans
      - name: cargo-deny licenses
        run: nix develop --command cargo deny check licenses
      - name: cargo-deny sources
        run: nix develop --command cargo deny check sources
